export enum ActionTypes {
  SET_INITIAL_STATE = 'SET_INITIAL_STATE',
  SET_PATIENT_PROFILE = 'SET_PATIENT_PROFILE',
  UPDATE_PATIENT_PROFILE = 'UPDATE_PATIENT_PROFILE',
  UPDATE_MEDICAL_HISTORY = 'UPDATE_MEDICAL_HISTORY',
  UPDATE_LIFE_STYLE = 'UPDATE_LIFE_STYLE',
}
